
### Resource Owner Password Credentials Grant Type ###

### 1. AccessToken, RefreshToken 발행
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YmFjdG9yaWE6cGFzc3dvcmQh # client_id:client_password (Not User)

grant_type=password&username=user1&password=pass&scope=read_profile


### 2. Resource 요청
GET http://localhost:8080/api/secret
Authorization: Bearer ########-####-####-####-############


###  3. AccessToken 만료시, 토큰 재발행
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YmFjdG9yaWE6cGFzc3dvcmQh # client_id:client_password (Not User)

grant_type=refresh_token&scope=read_profile&refresh_token=########-####-####-####-############
